apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jwks-public-access
rules:
  - nonResourceURLs: ["/openid/v1/jwks"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jwks-public-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jwks-public-access
subjects:
  - kind: User
    name: system:anonymous
    apiGroup: rbac.authorization.k8s.io